name: Scala CI

on:
  push:
    branches:
      - "**"
    # tags:
    #   - "**"

  pull_request:
    branches:
      - master

jobs:
  secrets:
    runs-on: ubuntu-latest
    outputs:
      secrets: ${{ steps.secrets.outputs.secrets }}
    steps:
      - name: secrets
        id: secrets
        env:
          HAS_PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE != '' }}
          HAS_ENCRYPTION_PASSWORD: ${{ secrets.ENCRYPTION_PASSWORD != '' }}
        shell: bash
        if: env.HAS_PGP_PASSPHRASE == 'true' && env.HAS_ENCRYPTION_PASSWORD == 'true'
        run: echo ::set-output name=secrets::true
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala: [3.1.3]
        module: [sqltest, db, async, bigdata]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Java and Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: 1.8.0

    - name: Scala ${{ matrix.scala }} Building ${{ matrix.module }}
      run: |
        export SCALA_VERSION=${{ matrix.scala }}
        echo "SCALA_VERSION='$SCALA_VERSION'"
        ./build/build.sh ${{ matrix.module }}

  release:
    if: ${{ github.event_name != 'pull_request' && needs.secrets.outputs.secrets }}
    runs-on: ubuntu-latest
    needs:
    - build
    - secrets
    strategy:
      matrix:
        scala: [3.1.3]
        module: [base, db, async, bigdata, publish]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Java and Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: 1.8.0
    - run: |
        export ENCRYPTION_PASSWORD=${{ secrets.ENCRYPTION_PASSWORD }}
        export PGP_PASSPHRASE=${{ secrets.PGP_PASSPHRASE }}
        export PULL_REQUEST=${{ !!github.event.pull_request }}
        echo "PULL_REQUEST='$PULL_REQUEST'"
        export BRANCH=$(git for-each-ref ${{ github.ref }} --format='%(refname:short)')
        echo "BRANCH='$BRANCH'"
        ./build/release.sh ${{ matrix.module }}
